### ISSUE TITLE
Broken link to hf-doc-builder

### ISSUE THREAD

**Issue by wch** [muellerzr/nbquarto#1]
On https://muellerzr.github.io/nbquarto/package_reference/processors, the link to hf-doc-builder is broken.

It points to https://github.comn/huggingface/doc-builder (notice the .comn).

**Comment by wch** [comment]
I also just noticed that the link to config.yaml on this page is broken:
https://muellerzr.github.io/nbquarto/getting_started.html

**Comment by muellerzr** [comment]
Thanks! Will fix today :)

**Comment by wch** [comment]
While I'm at it... it would be helpful if the [nbquarto](https://muellerzr.github.io/nbquarto/) site had an obvious link to the repository.

**Comment by muellerzr** [comment]
Agreed. Hadn't setup that key part of quarto sites yet 😅 (TBH *mildly* whelmed, it's awesome and yet terrifying how quickly this is getting eyes, didn't expect that at all 😅 )

**Comment by muellerzr** [comment]
Let me know if there's anything else odd or helpful I can do as well please, will be taking all of this evening + evenings rest of the week to flesh out a number of items 🙏 Appreciate a second set of eyes

**Comment by muellerzr** [comment]
Solved via #2
